name: run Uniqlochecker.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          pip install -r requirements.txt
          
      - name: execute py script # run py file
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TOKEN: ${{ secrets.TOKEN }}
        run: | 
          python Uniqlochecker.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git pull
          git commit -m "crongenerated"
          git push
